const firstNameList = ["John","William","Mary","Robert","James","Linda","Michael","Charles","George","David","Jennifer","Shirley","Richard","Barbara","Jason","Lisa","Betty","Christopher","Dorothy","Patricia","Helen","Jessica","Ashley","Donald","Anna","Joseph","Deborah","Frank","Mark","Matthew","Thomas","Debra","Susan","Margaret","Carol","Amanda","Brian","Joshua","Henry","Harry","Ruth","Amy","Emma","Edward","Daniel","Gary","Elizabeth","Melissa","Sandra","Michelle","Karen","Kimberly","Joan","Brittany","Judith","Larry","Cynthia","Andrew","Steven","Minnie","Nancy","Jacob","Donna","Justin","Sharon","Scott","Walter","Jeffrey","Timothy","Sarah","Heather","Ryan","Virginia","Brandon","Mildred","Ida","Kathleen","Tyler","Angela","Kevin","Arthur","Nicholas","Alice","Carolyn","Florence","Doris","Bertha","Ethel","Willie","Pamela","Emily","Kenneth","Fred","Clara","Frances","Annie","Jerry","Albert","Paul","Eric","Dennis","Austin","Stephanie","Adam","Marie","Judy","Jeremy","Samantha","Joyce","Jonathan","Nicole","Harold","Bessie","Zachary","Lori","Anthony","Ella","Brenda","Stephen","Tammy","Cheryl","Diane","Kathy","Hannah","Evelyn","Grace","Raymond","Madison","Lillian","Kelly","Nellie","Jack","Dolores","Laura","Megan","Taylor","Ethan","Cora","Martha","Lauren","Edna","Kyle","Crystal","Gladys","Clarence","Gregory","Mabel","Jean","Marilyn","Alexis","Tracy","Julie","Christina","Alexander","Carrie","Rebecca","Christine","Cindy","Tiffany","Rose","Cody","Hazel","Janet","Maude","Debbie","Amber","Teresa","Kayla","Danielle","Isabella","Billy","Lois","Gerald","Rachel","Gertrude","Marjorie","Beverly","Louise","Janice","Samuel","Tina","Pearl","Dawn","Ava","Shannon","Eugene","Dewey","Mattie","Irene","Catherine","Erin","Todd","Gloria","Olivia","Roy","Jennie","Chelsea","Sophia","Edith"];
const lastNameList = ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Morales","Murphy","Cook","Rogers","Gutierrez","Ortiz","Morgan","Cooper","Peterson","Bailey","Reed","Kelly","Howard","Ramos","Kim","Cox","Ward","Richardson","Watson","Brooks","Chavez","Wood","James","Bennett","Gray","Mendoza","Ruiz","Hughes","Price","Alvarez","Castillo","Sanders","Patel","Myers","Long","Ross","Foster","Jimenez","Powell","Jenkins","Perry","Russell","Sullivan","Bell","Coleman","Butler","Henderson","Barnes","Gonzales","Fisher","Vasquez","Simmons","Romero","Jordan","Patterson","Alexander","Hamilton","Graham","Reynolds","Griffin","Wallace","Moreno","West","Cole","Hayes","Bryant","Herrera","Gibson","Ellis","Tran","Medina","Aguilar","Stevens","Murray","Ford","Castro","Marshall","Owens","Harrison","Fernandez","Mcdonald","Woods","Washington","Kennedy","Wells","Vargas","Henry","Chen","Freeman","Webb","Tucker","Guzman","Burns","Crawford","Olson","Simpson","Porter","Hunter","Gordon","Mendez","Silva","Shaw","Snyder","Mason","Dixon","Munoz","Hunt","Hicks","Holmes","Palmer","Wagner","Black","Robertson","Boyd","Rose","Stone","Salazar","Fox","Warren","Mills","Meyer","Rice","Schmidt","Garza","Daniels","Ferguson","Nichols","Stephens","Soto","Weaver","Ryan","Gardner","Payne","Grant","Dunn"];

export const getRandomFirstName = (): string => {
  return firstNameList[Math.floor(Math.random() * firstNameList.length)];
}

export const getRandomLastName = (): string => {
  return lastNameList[Math.floor(Math.random() * lastNameList.length)];
}